version: '3.4'

networks:
  eknetwork:

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - eknetwork
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:9.3.8
    container_name: grafana
    networks:
      - eknetwork
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    image: grafana/k6:latest
    container_name: k6
    networks:
      - eknetwork
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./k6test:/scripts
    entrypoint: ["k6", "run", "/scripts/senario_test.js"]
    depends_on:
      - app
