spring:
  application:
    name: hhplus
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: Asia/Seoul
---
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/hhplus?characterEncoding=UTF-8
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  data:
    redis:
      host: redis
      port: 6379

---
# implementation("org.springframework.kafka:spring-kafka")
# spring-kafka 라이브러리에 yaml 의 spring.kafka.* 기반의 AutoConfiguration 이 들어있음.
spring:
  kafka:
    bootstrap-servers: kafka:9094 #${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: PLAINTEXT
      request.timeout.ms: 300000
      retry.backoff.ms: 60000
      auto:
        offset.reset: earliest
        register.schemas: false
        create.topics.enable: true
      use.latest.version: true
      basic.auth.credentials.source: USER_INFO
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 5
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        enable-auto-commit: false
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual
---
commerce-api:
  payment:
    topic-name: commerce.payment-success-event.v1